networks:
  monitoring:

services:
  # -------------------
  # Application Stack
  # -------------------
  go-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9091:9091" # Prometheus metrics
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=go-crud-app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=appdb
      - REDIS_ADDR=redis:6379
    networks:
      - monitoring
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------
  # Observability Stack
  # ---------------------------
  prometheus:
    image: prom/prometheus:v2.47.1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/etc/prometheus
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.26.0
    ports:
      - "9093:9093"
    volumes:
      - ./etc/alertmanager:/config
    command: --config.file=/config/config.yml
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./etc/loki:/etc/loki
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.2.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./etc/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Tempo
      - "4317:4317" # OTLP gRPC
    networks:
      - monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    command: [--config=/etc/otel-collector-config.yml]
    volumes:
      - ./etc/otel:/etc
    ports:
      - "13133:13133" # health_check
    depends_on:
      - tempo
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
      - ./etc/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    environment:
      - DATA_SOURCE_NAME=postgresql://user:password@postgres:5432/appdb?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - monitoring

  redis_exporter:
    image: oliver006/redis_exporter:v1.55.0
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    networks:
      - monitoring

volumes:
  postgres-data:
